### ISSUE TITLE
clientapi not working

### ISSUE THREAD

**Issue by imadarif** [voximplant/apiclient-nodejs#1]
client = new VoximplantApiClient("./credentials.json"); // this line not working.
    client has nothing. 
    client.onReady = function () {
    // Add a new user.

    client.Users.addUser({
        userName: req.query.phoneNumber,
        userDisplayName: req.query.displayName,
        userPassword: req.query.password,
        mobileNumber: req.query.phoneNumber,
        applicationId: voximplant_cred.application_id,
        applicationName: "abc"
    })
        .then(ev => console.log(ev))
        .catch(err => console.error(err));
}

**Comment by irbisadm** [comment]
Hello @imadarif ! What version of the node.js you use?

**Comment by UdumiziSolomon** [comment]
Did you fix the issue?...
