### ISSUE TITLE
reading the `pathToCredentials` with readFile instead of readFileSync

### ISSUE THREAD

**Issue by laguna-gabi** [voximplant/apiclient-nodejs#15]
when creating a `VoximplantApiClient` in the constructor you are initializing `this.key` object of the json by reading from the `pathToCredentials` with the following line
```
  fs.readFile(path, 'utf8', (err, data) => {
      if (err)
          throw err;
      this.key = JSON.parse(data);
      if (this.onReady)
          this.onReady(this);
  });
```
This creates a promise inside a constructor that takes time and in a scenario where you create the credentials file right before creating the `VoximplantApiClient` and then right after that try to use the client you get the following error:
```
@voximplant/apiclient-nodejs/dist/index.js:2354
        const tokenData = { iss: this.key.account_id, iat: nowTS, exp: nowTS + 64 };
                                          ^
TypeError: Cannot read properties of undefined (reading 'account_id')
```
you can solve that by using readFileSync instead.
```
  try {
    const data = fs.readFileSync(path, 'utf8')
    this.key = JSON.parse(data);
  } catch (err) {
    throw err
  }
```

**Comment by Olya-Nik** [comment]
It is implemented in another way: this.onReady is called in callback of fs.readFile
```
      if (this.onReady)
          this.onReady(this);
```
so in order to use the client you should define onReady function as described in Readme:
```
const client = new VoximplantApiClient();
client.onReady = function () {
  // Start the scripts from the account.
  client.Scenarios.startScenarios({ ruleId: '1', scriptCustomData: 'mystr' })
    .then((ev) => console.log(ev))
    .catch((err) => console.error(err));
};
```

**Comment by laguna-gabi** [comment]
@Olya-Nik the problem with that is that if i have for example an api call on my backend that when its called im creating a user in voximplant using the client, and if the client did not finish initiating there will be an error.
there is no way to wait for the client to be created before proceeding.

**Comment by Olya-Nik** [comment]
Consider wrapping client initiating in Promise, it can solve the problem, for example:
```
let client;
function init () {
    return new Promise((resolve) => {
        client = new VoximplantApiClient('a7b6c96b-093d-42c0-8444-cdc0ea15074c_private.json');

        client.onReady = function () {
            resolve()
        };
    })
}
```
```
async function someRequest() {
    await init()
    client.Applications.getApplications({})
        .then((ev) => console.log(ev))
        .catch((err) => console.error(err));
}
```
