### ISSUE TITLE
Initialise VoximplantApiClient without storing any credential files?

### ISSUE THREAD

**Issue by bizmedia** [voximplant/apiclient-nodejs#2]
Ho to initialise VoximplantApiClient without storing any credential files but using only .env?
Something like:
```js
const voxClient = new VoximplantApiClient({
  account_id: process.env.VOXIMPLANT_ACCOUNT_ID || "",
  api_key: process.env.VOXIMPLANT_ACCOUNT_API_KEY || ""
});
```

**Comment by irbisadm** [comment]
Sorry but you only can do this with file.

**Comment by evenfrost** [comment]
And why so? Of course, you can for example map values in JSON file to env variables with `dotenv`, but why make this so difficult? Why not just specify the params as an object?
