### ISSUE TITLE
vulnerability in jsonwebtoken 8.5.1

### ISSUE THREAD

**Issue by hadasmeitav** [voximplant/apiclient-nodejs#20]
Hi, there's a vulnerability in a library you're using `jsonwebtoken` version 8.5.1
It is recommended to use version 9.0.0

This affects our readiness to a certain mandatory steps in our development, which we can't do at the moment.
can you upgrade this dependency? 

<img width="679" alt="Screen Shot 2023-01-15 at 16 41 13" src="https://user-images.githubusercontent.com/9152018/212547419-87e9721b-28b6-401f-8d1a-89e61d4dcb42.png">

**Comment by NikolasMelui** [comment]
Hi there! Thanks a lot for the issue and for participating in the project!
This issue will be solved in the next package version.
See you! ✌️
