### ISSUE TITLE
Incompatible with Node ESM

### ISSUE THREAD

**Issue by ramijarrar** [voximplant/apiclient-nodejs#26]
This library is currently incompatible with Node ESM (which includes any Typescript users on `node16` or `nodenext` module mode) due to the default export not also setting `module.exports` in the generated CJS output.

More information about this issue is available here: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSOnlyExportsDefault.md.

The solution is to make the following changes to the untranspiled source:
```diff
-export default class VoximplantApiClient {
+class VoximplantApiClient {
...
}
+
+export = VoximplantApiClient;
```

**Comment by ramijarrar** [comment]
A detailed explanation of the suggested solution is also available in the official Typescript docs: https://www.typescriptlang.org/docs/handbook/modules/appendices/esm-cjs-interop.html#library-code-needs-special-considerations

> Users will detect a misconfigured module smell if they have to access the `.default` property of a default import, and if they’re trying to write code that will run both in Node.js and a bundler, they might be stuck. Some third-party TypeScript transpilers expose options that change the way default exports are emitted to mitigate this difference, but they don’t produce their own declaration (`.d.ts`) files, so that creates a mismatch between the runtime behavior and the type checking, further confusing and frustrating users. **Instead of using default exports, libraries that need to ship as CommonJS should use `export =` for modules that have a single main export**, or named exports for modules that have multiple exports:

**Comment by NikolasMelui** [comment]
Hi there! Thanks a lot for the issue (again 😄) and for participating in the project!
As I said, we have quite a few other ideas for improving this package that we would like to include in the next major version. This issue will be solved there too.
