### ISSUE TITLE
ClientAPI not working with create-react-app

### ISSUE THREAD

**Issue by y-yeah** [voximplant/apiclient-nodejs#3]
In React app with the node version 10.15.1, `fs` module does not work. 
I got the following error in the browser when running `react-scripts start`.

**Error**
```
×
TypeError: fs.readFile is not a function
new VoximplantApiClient
node_modules/@voximplant/apiclient-nodejs/dist/index.js:6192
  6189 |   }
  6190 | };
  6191 | const path = process.env.VOXIMPLANT_CREDENTIALS || pathToCredentials;
> 6192 | fs.readFile(path, 'utf8', (err, data) => {
       | ^  6193 |   if (err) throw err;
  6194 |   this.key = JSON.parse(data);
  6195 |   if (this.onReady) this.onReady(this);
```

**Suggestion**
Instead of using the path and fs, have a user import the credentials file.

Front-end
```
import credentials from "path/to/credentials.json";

const VoximplantApiClient = require("@voximplant/apiclient-nodejs").default;
const client = new VoximplantApiClient(credentials); // Here we had a TypeError
```

Line 14- in `src/index.tsx` (apiclient-nodejs)
```
  constructor(credentials?: VoximplantApiClient["key"],private host?:string){
    this.key = credentials
    if(this.onReady)
      this.onReady(this)
  }
```

**Comment by irbisadm** [comment]
Sure. You have the issue because this library is back-end only. Please use https://www.npmjs.com/package/voximplant-websdk for building a front-end client.

**Comment by y-yeah** [comment]
Ah. Thank you for pointing it out.
I was trying to run this backend code locally to see if this really works. It’d be helpful for developers if you’d specify that this library is only for backend node, in README.
