### ISSUE TITLE
PhoneNumbers.getPhoneNumbers returns booleans as strings

### ISSUE THREAD

**Issue by sebasgavi** [voximplant/apiclient-nodejs#9]
All the booleans in this result are strings, haven't tested it in other functions.

![image](https://user-images.githubusercontent.com/4133176/148097695-eaa0b1df-2a52-48eb-8feb-1c202dc349a5.png)

**Comment by NikolasMelui** [comment]
Hi there! Thanks a lot for this issue! 💪
This is a really serious bug and to fix it we need to make a breaking change, so we will fix it in the next major version.
We will notify you as soon as the new version is available ✌️

**Comment by NikolasMelui** [comment]
@sebasgavi the new major version is available, thx for the participating 💪
https://github.com/voximplant/apiclient-nodejs/releases/tag/v3.0.0
